### PR TITLE
WIP: Beat Saber 1.19 compatability

### PR DESCRIPTION
**Pull request by blackfisch**
## Changes

- Updated Code to BS 1.19 API changes

## Known Issues

- Creating Servers does not work (maybe netcode or server issue)
- Chat might be broken (cannot confirm -> servers not working)

### CODE REVIEW

**Comment by Kevman95** [comment]
@Goobwabber

**Comment by iT3g4n** [comment]
Why has this not been accepted yet? Is the owner of the plugin not active anymore?

**Comment by Kevman95** [comment]
We already have been working on support and fixes which will be on the main branch soon.

Our Discord in our Readme is the best place for updates on our progress.  This repo doesn't typically see public change till all the rest of our components are ready which you can check on the other repos we have.

**Comment by NCSGeek** [comment]
> We already have been working on support and fixes which will be on the main branch soon.
> 
> Our Discord in our Readme is the best place for updates on our progress. This repo doesn't typically see public change till all the rest of our components are ready which you can check on the other repos we have.

I see no discord link in your fork's readme.md.

**Comment by Kevman95** [comment]
@NCSGeek

https://github.com/BeatTogether/BeatTogether#readme

It's in the first paragraph.

"Feel free to join our Discord! https://discord.com/invite/gezGrFG4tz (Support, Coordinating games with friends, etc)"

**Comment by NCSGeek** [comment]
> @NCSGeek
> 
> https://github.com/BeatTogether/BeatTogether#readme
> 
> It's in the first paragraph.
> 
> "Feel free to join our Discord! https://discord.com/invite/gezGrFG4tz (Support, Coordinating games with friends, etc)"

Thanks. Somehow I found myself at the wrong repo it seems.

**Pull request closed without merging**
